apiVersion: v1
kind: LimitRange
metadata:
  name: db-limits
  namespace: database
spec:
  limits:
    - max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 500m
        memory: 500Mi
      type: Container

